### ISSUE TITLE
Allow `gu install` of other items

### ISSUE THREAD

**Issue by dmikusa** [paketo-buildpacks/graalvm#199]
Right now when the GraalVM buildpack runs, it installs GraalVM and then can optionally install the Native image substrate VM. It uses the `gu` tool to install the native image tools.

GraalVM has other items that it can `gu install`, such as support for alternative languages like Python or Javascript. These don't work at the moment because they are additional items that must be installed and the buildpack does not provide a way to install them at the moment.

This is an enhancement request to allow other tools to be `gu install`ed.

The use case is for running things like Python ML code through the JVM, which [can be faster](https://www.graalvm.org/python/).

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by fniephaus** [comment]
FYI: https://github.com/oracle/graal/issues/6855

**Comment by dmikusa** [comment]
Closing this, see the previous comment.
