### ISSUE TITLE
Will Java 16 be supported?

### ISSUE THREAD

**Issue by UkonnRa** [paketo-buildpacks/graalvm#76]
Since GraalVM supports Java 16 (https://www.graalvm.org/release-notes/21_1/), just wondering will the buildpack support Java 16 too?

**Comment by dmikusa-pivotal** [comment]
It's something I can look into. It's technically possible to include as long as there are upstream releases we can use, but it seems very early days according to the release notes. I would want to see if this works for things like our test suite and common use cases, like building Spring Boot apps before we include it.

>Java 16 (experimental) support: The GraalVM distributions based on Oracle Java 16 and OpenJDK 16 are available for download with several known limitations.

**Comment by sdeleuze** [comment]
See [related Spring Native comment](https://github.com/spring-projects-experimental/spring-native/issues/720#issuecomment-837979880). I would be in favor of waiting Java 17 (LTS) support for introducing the support in buildpack and officially on Spring Native (where we still document supporting only Java 8 and 11).

Notice that at that point we may remove Java 8 support, and maybe even Java 11 one to focus on Java 17 (which can compile most Java 8 and Java 11 applications).

**Comment by dmikusa-pivotal** [comment]
I have added support for Java 16 into GraalVM CNB version 6.3.0, which was just released. Java 16 is still marked as experimental upstream with GraalVM. As such, it's not the default (probably never will be) and should be used at your own risk. i.e. Do not use it in production.
